// <auto-generated />
using System;
using BankingRESTApi.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingRESTApi.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20210707172421_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("BankingRESTApi.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<long?>("ContaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BankingRESTApi.Models.Conta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("Agencia")
                        .HasColumnType("int")
                        .HasColumnName("Agencia");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Limite");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Saldo");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("BankingRESTApi.Models.Cliente", b =>
                {
                    b.HasOne("BankingRESTApi.Models.Conta", "Conta")
                        .WithOne("Cliente")
                        .HasForeignKey("BankingRESTApi.Models.Cliente", "ContaId");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("BankingRESTApi.Models.Conta", b =>
                {
                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
